version: "3.9"
services:
  postgres:
    image: docker.io/postgres:14
    restart: unless-stopped
    # user: postgres:postgres
    # user: "974:974"
    ports:
      - target: 5432
        published: 5432
        mode: host
    volumes:
      - postgres:/var/lib/postgresql/data
      - ../data/postgres/initdb.d:/initdb.d
      - /home/marc/backup:/backup
      - ../data/postgres/certs:/var/lib/postgresql/certs
    env_file:
      - ../data/secrets/postgres.env
    command: |
      postgres
      -c log_statement=all
      -c log_destination=stderr
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3

  pgagent:
    image: docker.io/chiavegatto/postgres-pgagent
    entrypoint: /bin/sh -c
                "/tmp/wait-for-it.sh postgres:5432 --timeout=30 &&
                psql -U postgres -h postgres -p 5432 -d postgres -c 'CREATE EXTENSION IF NOT EXISTS pgagent;' &&
                pgagent -f hostaddr=postgres dbname=postgres user=postgres port=5432"
    environment:
      TIMEZONE: Europe/Paris
    env_file:
      - ../data/secrets/postgres.env
    networks:
      - postgres

  backup:
    image: docker.io/kartoza/pg-backup:14-3.1
    env_file:
      - ../data/secrets/pg_backup.env
    networks:
      - postgres
    volumes:
      - /srv/pg-backup:/backups

  # https://github.com/prodrigestivill/docker-postgres-backup-local
  # restore:
  # docker exec --tty --interactive $CONTAINER /bin/sh -c "zcat $BACKUPFILE | psql --username=$USERNAME --dbname=$DBNAME -W"
  pgbackups:
    image: docker.io/prodrigestivill/postgres-backup-local
    restart: unless-stopped
    # user: postgres:postgres
    volumes:
      - /srv/pgbackups:/backups
    # links:
    #   - postgres
    # depends_on:
    #   - postgres
    networks:
      - postgres
    env_file:
      - ../data/secrets/pgbackups.env

volumes:
  postgres:

networks:
  postgres:
    external: true
